### ISSUE TITLE
Adjust README.Rmd template to better explain how to download a raw CSV from a browser window

### ISSUE THREAD

**Issue by larnsce** [openwashdata-dev/washr#18]
To download the CSV file, you need to:

1. Click Download CSV -> a windows opens that displayes the CSV in your browser
2. Right-click anywhere inside the window and select "Save Page As..."
3. Save the file in a folder of your choice

Implement here: https://github.com/openwashdata-dev/washr/blob/fa735cffb46fe40d0771600475e4e2fba60b12df/inst/templates/README.Rmd#L57

**Comment by bonschorno** [comment]
Thanks, just added this list to the README template.
