### ISSUE TITLE
Roxygen for new functions

### ISSUE THREAD

**Issue by yashdubey132** [openwashdata-dev/washr#38]
Helper functions won't export until roxygen is added and NAMESPACE includes exports for each

**Comment by larnsce** [comment]
Can we support you with this one?

**Comment by yashdubey132** [comment]
I think I can manage but would appreciate any feedback on the documentation

**Comment by yashdubey132** [comment]
Updated in https://github.com/openwashdata/washr/commit/9cf6b9bd420a6ef56d3afe381127d1870e2c823e
