### ISSUE TITLE
Checks fail because metadata folder is "non-standard"

### ISSUE THREAD

**Issue by yashdubey132** [openwashdata-dev/washr#42]
When `devtools::check()` is executed, 1 error occurs.

1. The error is due to the fact that the metadata folder is not expected in the data folder. 
2. Advice from the check is to move it to inst/extdata. However, this defeats the purpose of dataspice keeping the data and metadata together. 
3. Possible resolution could be to move the metadata to the data-raw folder instead as the dictionary.csv file also exists there. 
4. JSON-LD file should be stored in the same folder.

**Comment by yashdubey132** [comment]
@larnsce please let me know your thoughts

**Comment by larnsce** [comment]
I think it might be possible to add it to the .Rbuildignore file. I have had similar issues before and solved it like that.

**Comment by yashdubey132** [comment]
- [ ] Update add_metadata() function with functionality to update .RBuildignore

**Comment by yashdubey132** [comment]
Fixed in commit: https://github.com/openwashdata/washr/commit/69a7c0f4ff1e9668f9ec71b5cbe00710322577e4
