### ISSUE TITLE
generated README appears an NA dataset in the summary table

### ISSUE THREAD

**Issue by mianzg** [openwashdata-dev/washr#7]

**Comment by mianzg** [comment]
The util function did not load the full data object. Fixed here: d20b71d

**Comment by mianzg** [comment]
Not a bug from the functions. 

It can be various reasons, but essentially, the developers manually modified the dictionary csvfile at the bottom. There should be no newlines at the bottom of the file. Maybe add a sanity check on dictionary.csv in future version

**Comment by larnsce** [comment]
Yes, that could be a good case for using a testing function of the testthat R package: https://github.com/r-lib/testthat

**Comment by mianzg** [comment]
It cannot be tested because the bad result is not from the washr functions
